### ISSUE TITLE
Winston logger error

### ISSUE THREAD

**Issue by ericraymond** [martysweet/cfn-lint#117]
/usr/local/lib/node_modules/cfn-lint/node_modules/winston/lib/winston/common.js:162
        throw new Error([
        ^

Error: winston.Logger was moved in winston@3.0.0.
Use a winston.createLogger instead.
    at new <anonymous> (/usr/local/lib/node_modules/cfn-lint/node_modules/winston/lib/winston/common.js:162:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/cfn-lint/lib/logger.js:3:14)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)

**Comment by micmicsuarez** [comment]
Hi guys,

I encountered the same issue also.

Thanks,
Michael

**Comment by martysweet** [comment]
Ah, will have a patch released in the next couple of hours!

**Comment by martysweet** [comment]
@ericraymond @micmicsuarez This should now be fixed. Let me know if you have any problems. :+1:

**Comment by micmicsuarez** [comment]
Hi @martysweet.

It worked! :) 

Thanks,
Michael

**Comment by ericraymond** [comment]
That fixes that issue, but I get an error on parts.join not a function.  Will log another issue:

**Comment by ericraymond** [comment]
2018-03-12T17:43:27.037Z - error: uncaughtException: parts.join is not a function date=Mon Mar 12 2018 10:43:27 GMT-0700 (PDT), pid=36819, uid=501, gid=20, cwd=/Users/ericraymond/src/omni/mm/mm-spark/ci/sjs/config/emr, execPath=/usr/local/Cellar/node/9.8.0/bin/node, version=v9.8.0, argv=[/usr/local/Cellar/node/9.8.0/bin/node, /usr/local/bin/cfn-lint, validate, cloudformation/mm.yaml], rss=42012672, heapTotal=23224320, heapUsed=15349432, external=16800, loadavg=[1.87548828125, 2.17919921875, 2.13623046875], uptime=261223, trace=[column=18, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=fnJoin, line=1053, method=null, native=false, column=16, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=doIntrinsicJoin, line=596, method=null, native=false, column=20, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=resolveIntrinsicFunction, line=519, method=null, native=false, column=38, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=471, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=5, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=resolveReferences, line=441, method=null, native=false], stack=[TypeError: parts.join is not a function,     at fnJoin (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:1053:18),     at doIntrinsicJoin (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:596:16),     at resolveIntrinsicFunction (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:519:20),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:471:38),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at resolveReferences (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:441:5)]
