### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by john-aws** [martysweet/cfn-lint#188]
A YAML template with the following:

    AvailabilityZone: !Select [ 0, !GetAZs ]

causes the following internal error:

```
Unable to parse template! Use --verbose for more information.
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at doIntrinsicGetAZs (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:812:26)
    at resolveIntrinsicFunction (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:667:20)
    at doIntrinsicSelect (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:892:24)
    at resolveIntrinsicFunction (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:681:20)
    at recursiveDecent (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:606:38)
    at recursiveDecent (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:616:13)
    at recursiveDecent (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:616:13)
    at recursiveDecent (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:616:13)
    at recursiveDecent (/Users/john/.nvm/versions/node/v8.10.0/lib/node_modules/cfn-lint/src/validator.ts:616:13)
```

The provided GetAZs construct is accepted by CloudFormation.

**Comment by martysweet** [comment]
This should just be a case of picking up this edge case within the `doIntrinsicGetAZs` method. This version of the shorthand is currently not taken into account.

https://github.com/martysweet/cfn-lint/blob/master/src/validator.ts#L810-L811

Something like

```
if is an argument is actually present
 process argument (current code)
else don't bother with arguments
 current else statement
```
