### ISSUE TITLE
Can not read property'hasOwnProperty' of null

### ISSUE THREAD

**Issue by concon121** [martysweet/cfn-lint#68]
Getting this error from a fresh install of cfn-lint version 1.1.7.

The cloudformation template i'm using is a valid json format template which has already been deployed successfully.

```
root@DESKTOP-9JIN1GI:/mnt/c/workspace/andover-pipelinebot# npm install -g cfn-lint
/usr/bin/cfn-lint -> /usr/lib/node_modules/cfn-lint/lib/index.js
/usr/lib
└── cfn-lint@1.1.7

root@DESKTOP-9JIN1GI:/mnt/c/workspace/andover-pipelinebot# cfn-lint --version
1.1.7
root@DESKTOP-9JIN1GI:/mnt/c/workspace/andover-pipelinebot# cfn-lint validate .serverless/cloudformation-template-update-stack.json
2017-10-31T14:35:12.455Z - error: uncaughtException: Cannot read property 'hasOwnProperty' of null date=Tue Oct 31 2017 14:35:12 GMT+0000 (STD), pid=1178, uid=0, gid=0, cwd=/mnt/c/workspace/andover-pipelinebot, execPath=/usr/bin/node, version=v6.11.3, argv=[/usr/bin/node, /usr/bin/cfn-lint, validate, .serverless/cloudformation-template-update-stack.json], rss=26845184, heapTotal=19972096, heapUsed=10396944, external=69450, loadavg=[0.5185546875, 0.57763671875, 0.5859375], uptime=103911, trace=[column=16, file=/usr/lib/node_modules/cfn-lint/lib/resourcesSpec.js, function=Object.isAdditionalPropertiesEnabled, line=121, method=isAdditionalPropertiesEnabled, native=false, column=49, file=/usr/lib/node_modules/cfn-lint/lib/validator.js, function=checkResourceProperty, line=928, method=null, native=false, column=21, file=/usr/lib/node_modules/cfn-lint/lib/validator.js, function=checkProperty, line=1049, method=null, native=false, column=17, file=/usr/lib/node_modules/cfn-lint/lib/validator.js, function=checkResourceProperty, line=973, method=null, native=false, column=21, file=/usr/lib/node_modules/cfn-lint/lib/validator.js, function=checkProperty, line=1049, method=null, native=false, column=17, file=/usr/lib/node_modules/cfn-lint/lib/validator.js, function=checkResourceProperty, line=973, method=null, native=false, column=9, file=/usr/lib/node_modules/cfn-lint/lib/validator.js, function=null, line=919, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=27, file=/usr/lib/node_modules/cfn-lint/lib/validator.js, function=checkEachProperty, line=918, method=null, native=false, column=17, file=/usr/lib/node_modules/cfn-lint/lib/validator.js, function=checkResourceProperties, line=902, method=null, native=false], stack=[TypeError: Cannot read property 'hasOwnProperty' of null,     at Object.isAdditionalPropertiesEnabled (/usr/lib/node_modules/cfn-lint/lib/resourcesSpec.js:121:16),     at checkResourceProperty (/usr/lib/node_modules/cfn-lint/lib/validator.js:928:49),     at checkProperty (/usr/lib/node_modules/cfn-lint/lib/validator.js:1049:21),     at checkResourceProperty (/usr/lib/node_modules/cfn-lint/lib/validator.js:973:17),     at checkProperty (/usr/lib/node_modules/cfn-lint/lib/validator.js:1049:21),     at checkResourceProperty (/usr/lib/node_modules/cfn-lint/lib/validator.js:973:17),     at /usr/lib/node_modules/cfn-lint/lib/validator.js:919:9,     at Array.forEach (native),     at checkEachProperty (/usr/lib/node_modules/cfn-lint/lib/validator.js:918:27),     at checkResourceProperties (/usr/lib/node_modules/cfn-lint/lib/validator.js:902:17)]
root@DESKTOP-9JIN1GI:/mnt/c/workspace/andover-pipelinebot# cfn-lint validate .serverless/cloudformation-template-update-stack.json --pseudo AWS::Region=eu-west-1,AWS::AccountId=12345
```

**Comment by martysweet** [comment]
Hi @concon121,

Would it be possible for you to try v1.2.0? I was unable to reproduce your issue with v1.1.7 on your  NodeJS version.

If this still doesn't work, would it be possible to provide the template? (or an abstraction of it which causes the error).

Thanks,
Marty
